version: "3.9"
services:
    streamlit:
        image: nextmet
        build:
          context: .
          dockerfile: Dockerfile
          args:
            NEXTMET_BUILD_VERSION: docker_compose_version
        env_file:
          - .streamlit/secrets.toml
        ports:
          - '8501:8501'