name: Docker Image CI

env:
  IMAGE_VERSION: 0.0.${{github.run_number}}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y jq unzip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          nickmanc/nextmet
          ghcr.io/${{ github.repository }}
          ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nextmet
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}},value=${{env.IMAGE_VERSION}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          NEXTMET_BUILD_VERSION=${{env.IMAGE_VERSION}}
          GOOGLE_ANALYTICS_TAG=${{vars.GOOGLE_ANALYTICS_TAG}}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
